import type { MetadataRoute } from 'next'

/**
 * Web App Manifest.
 *
 * Next 15 serves this at `/manifest.webmanifest` and auto-injects the
 * `<link rel="manifest">` tag into <head>.
 *
 * `display: 'standalone'` makes Voltwise launch full-screen from the home
 * screen on Android and iOS (when added via Share → Add to Home Screen).
 *
 * iOS 16.4+ notably requires `display: 'standalone'` for Web Push to work,
 * so installing this is also the unlock for Smart Guard on iPhones.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Voltwise — Iberian energy co-pilot',
    short_name: 'Voltwise',
    description:
      'Real-time OMIE prices, AI invoice audits, smart alerts for Portugal and Spain.',
    start_url: '/dashboard',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#0a0a0c',
    theme_color: '#0a0a0c',
    lang: 'pt',
    dir: 'ltr',
    categories: ['utilities', 'productivity', 'finance'],
    icons: [
      {
        src: '/icons/icon.svg',
        sizes: 'any',
        type: 'image/svg+xml',
        purpose: 'any',
      },
      {
        src: '/icons/icon-maskable.svg',
        sizes: 'any',
        type: 'image/svg+xml',
        purpose: 'maskable',
      },
      {
        // Auto-generated by `app/icon.tsx` — Next routes it to `/icon`.
        src: '/icon',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
    ],
    shortcuts: [
      {
        name: 'Dashboard',
        short_name: 'Dashboard',
        description: 'Live OMIE prices and Next Best Action',
        url: '/dashboard',
        icons: [{ src: '/icons/icon.svg', sizes: 'any', type: 'image/svg+xml' }],
      },
      {
        name: 'Auditor',
        short_name: 'Auditor',
        description: 'Audit your last electricity bill',
        url: '/auditor',
        icons: [{ src: '/icons/icon.svg', sizes: 'any', type: 'image/svg+xml' }],
      },
      {
        name: 'Alerts',
        short_name: 'Alerts',
        description: 'Smart Guard rules and recent fires',
        url: '/alerts',
        icons: [{ src: '/icons/icon.svg', sizes: 'any', type: 'image/svg+xml' }],
      },
    ],
    prefer_related_applications: false,
  }
}
